pipeline {
    agent any

    environment {
        AWS_ACCESS_TOKEN = credentials('aws-creds')
        AWS_ACCESS_REGION = 'ap-south-1'

    }
    stages {
        stage('preparation') {
            steps {
                git 'https://github.com/ikaushikdas/docker-demo.git'
            }
        }
        // stage('build') {
        //     steps {
              
        //         nodejs(nodeJSInstallationName: 'nodejs') {
        //             sh 'npm install'
        //             sh 'npm run test'                 

        //         }
                
        //     }
        // }
        // stage('Login to AWS ECS'){
           
        //     steps{
        //         sh 'aws ecr $AWS_ACCESS_TOKEN_PSW --region $AWS_ACCESS_REGION | docker login --username $AWS_ACCESS_TOKEN_USR --password-stdin 116361412831.dkr.ecr.ap-south-1.amazonaws.com'
        //     }  

        // }
        stage('Build Docker Image'){
           
            steps{
                script {
                dockerImage = docker.build 116361412831.dkr.ecr.ap-south-1.amazonaws.com/node-app + ":$BUILD_NUMBER"
                }
                //sh 'docker tag node-app:$BUILD_NUMBER 116361412831.dkr.ecr.ap-south-1.amazonaws.com/node-app:$BUILD_NUMBER'
               
            }  

        }
        stage('Push To ECS'){
           
            steps{
                //sh 'docker push 116361412831.dkr.ecr.ap-south-1.amazonaws.com/node-app:$BUILD_NUMBER'
                docker.withRegistry("https://116361412831.dkr.ecr.ap-south-1.amazonaws.com/node-app", "ecr:" + AWS_ACCESS_REGION + ":" + AWS_ACCESS_TOKEN) {
                    dockerImage.push()
                } 

        }
        
        
    }
    
}
