pipeline {
    agent any
    
    stages {
        stage('preparation') {
            steps {
                git 'https://github.com/ikaushikdas/docker-demo.git'
            }
        }

        stage('Login to AWS ECS'){
           
            steps{
                 sh 'aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 116361412831.dkr.ecr.ap-south-1.amazonaws.com'
            }  

        }
        stage('Build Docker Image'){
           
            steps{
                   sh 'docker build -t node-app .'
                   sh 'docker tag node-app:${BUILD_NUMBER} 116361412831.dkr.ecr.ap-south-1.amazonaws.com/node-app:${BUILD_NUMBER}'               
            }  

        }
        stage('Push To ECR'){
           
            steps{
                sh 'docker push 116361412831.dkr.ecr.ap-south-1.amazonaws.com/node-app:${BUILD_NUMBER}'
            } 

        }
        
        
    }
    
}
